apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic512bot
  labels:
    app: magic512bot
  namespace: buildkite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magic512bot
  template:
    metadata:
      labels:
        app: magic512bot
    spec:
      containers:
        - name: app
          image: bassmatt/magic512bot:latest
          envFrom:
          - secretRef:
            name: magic-512-bot-creds