apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic512bot
  labels:
    app: magic512bot
  namespace: buildkite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magic512bot
  template:
    metadata:
      labels:
        app: magic512bot
    spec:
      containers:
        - name: app
          image: "${DOCKER_IMAGE}"
          envFrom:
            - secretRef:
                name: magic-512-bot-creds
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m" 