[tool.poetry]
name = "card-lender"
version = "0.1.0"
description = ""
authors = ["mbass <mbass@atlassian.com>"]
readme = "README.md"
packages = [{include = "card_lender"}]

[tool.poetry.dependencies]
python = "^3.11"
discord-py = "^2.4.0"
python-dotenv = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
