#!/usr/bin/env bash

set -euo pipefail

# Download Kubectl Binary
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
chmod +x ./kubectl
mv ./kubectl /bin

# envsubst needed for enforcing manifest
apk add envsubst

export DOCKER_IMAGE="bassmatt/magic512bot:${BUILDKITE_BUILD_NUMBER}"

manifest="$(mktemp)"

echo '--- :kubernetes: Shipping'

envsubst < deployment.yml > "${manifest}"
kubectl apply -f "${manifest}"

echo '--- :zzz: Waiting for deployment'
kubectl wait --for condition=available --timeout=300s -f "${manifest}"
