#!/usr/bin/env bash

set -euo pipefail

manifest="deployment.yml"

echo '--- :kubernetes: Shipping'

kubectl apply -f "${manifest}"

echo '--- :zzz: Waiting for deployment'
kubectl wait --for condition=available --timeout=300s -f "${manifest}"
