#!/usr/bin/env bash

set -euo pipefail

DOCKER_IMAGE=bassmatt/magic512bot:latest

docker pull $DOCKER_IMAGE

manifest="$(mktemp)"

echo '--- :kubernetes: Shipping'

envsubst < deployment.yml > "${manifest}"
kubectl apply -f "${manifest}"

echo '--- :zzz: Waiting for deployment'
kubectl wait --for condition=available --timeout=300s -f "${manifest}"
