steps:
  - label: "Example Test"
    command: echo "Hello2!"
    agents:
      queue: kubernetes
    plugins:
      - kubernetes:
          gitEnvFrom:
            - secretRef:
                name: my-private-git-ssh-key